#include "nu2api/nucore/nuapi.h"
#include "nu2api/nu3d/android/nutex_android.h"
#include "nu2api/nu3d/ShaderManagerOpenGL.h"
#include "gamelib/util/CRC16.h"
#include "gamelib/util/gamelib_util_types.h"
#include <new>
/*
 * Shader manager.
 *
 * Faithful, readable reimplementation of the original iOS shader manager.
 * The original built shader keys from a 104-byte material block hashed with
 * a CRC-16 pair, remapped them through redirect tables and cached compiled
 * GL programs in a fixed-size slot array.
 *
 * This file keeps the same hashing, remapping and caching behaviour but
 * presents it as ordinary C++: named constants, typed storage helpers and
 * linear control flow instead of goto/union tricks and hex-offset comments.
 */

#include "nushader_plain.h"
#include "nu2api/nu3d/nu2api_nu3d_types.h"
#include "nushader.h"
#include "nu2api/nu3d/nutex.h"
#include "nu2api/nu3d/android/nuiosdl_gl.h"
#include "nu2api/nu3d/android/nutex_android.h"
#include "nu2api/nu3d/android/nutex_ios_ex.h"

// NuShaderObjectInit overload used by the manager.
void NuShaderObjectInit(nushaderobject_s *, const nushaderobjectkey_s *, i32, u32, u32, eSHADERVERSION);

using nu2api::HashRedirect;
using nu2api::LoadedUniqueShaderRecord;
using nu2api::ShaderMtlDescFilterPlain;

void *g_shaderManager = nullptr;
char g_shaderSaveFolder[256] = "shaders";

#include <GLES2/gl2.h>
#include <cstdio>
#include <cstring>

#include "nu2api/nufile/nufile.h"
#include "nu2api/nuandroid/ios_graphics.h"

extern i32 file_criticalsection;
extern i32 RemoveNormalMaps;
extern i32 RemoveDirectionalMaps;
#include "nu2api/nucore/nuthread.h"

// Redirect / preloaded tables are generated byte-exact from the original
// binary. They define g_vertexShaderRedirects, g_pixelShaderRedirects,
// g_shaderProgramRedirects, g_loadedUniqueVertexShaders and
// g_loadedUniquePixelShaders.
#include "nudlist_tables_gen.inc"

namespace nu2api {

    // ---------------------------------------------------------------------------
    // Manager storage. Host builds use the typed native layout so pointers and
    // object strides follow the host ABI.
    static constexpr u32 kSlotCount = 0x190;
    typedef ShaderManagerOpenGL ShaderManagerStorage;

    inline ShaderManagerStorage *Manager() {
        return static_cast<ShaderManagerStorage *>(g_shaderManager);
    }
    inline NUSHADEROBJECT *SlotPtr(i32 id) {
        return &Manager()->slots[id];
    }
    inline i32 &SlotRefCount(NUSHADEROBJECT *slot) {
        return slot->glsl.base.field1;
    }
    inline u32 &SlotProgramKey(NUSHADEROBJECT *slot) {
        return slot->glsl.base.key;
    }
    inline GLuint &SlotGlProgram(NUSHADEROBJECT *slot) {
        return slot->glsl.program;
    }
    inline i32 &ManagerLastAllocated() {
        return Manager()->last_allocated;
    }
    inline NUSHADEROBJECT *&ManagerBoundSlot() {
        return Manager()->bound_slot;
    }

    // ---------------------------------------------------------------------------
    // Uniform table
    // ---------------------------------------------------------------------------

    // Original 101 semantic records, 0x5c bytes each on the target ABI.
    ShaderUniformRecord g_shaderUniforms[101] = {
        {{nullptr,
          "layer0_sampler",
          {0x0u, 0x0u, 0x2u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{nullptr,
          "layer1_sampler",
          {0x0u, 0x0u, 0x2u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{nullptr,
          "layer2_sampler",
          {0x0u, 0x0u, 0x2u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{nullptr,
          "layer3_sampler",
          {0x0u, 0x0u, 0x2u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{nullptr,
          "specular_sampler",
          {0x0u, 0x0u, 0x2u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{nullptr,
          "specular2_sampler",
          {0x0u, 0x0u, 0x2u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{nullptr,
          "surface_sampler",
          {0x0u, 0x0u, 0x2u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{nullptr,
          "surface2_sampler",
          {0x0u, 0x0u, 0x2u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{nullptr,
          "detailSurface_sampler",
          {0x0u, 0x0u, 0x2u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"vertexFetch_sampler",
          nullptr,
          {0x0u, 0x0u, 0x1u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{nullptr,
          "perm_sampler",
          {0x0u, 0x0u, 0x2u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{nullptr,
          "permgrad_sampler",
          {0x0u, 0x0u, 0x2u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{nullptr,
          "vtfNormal_sampler",
          {0x0u, 0x0u, 0x2u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{nullptr,
          "diffenvmap_samplerCube",
          {0x0u, 0x0u, 0x2u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{nullptr,
          "envmap_samplerCube",
          {0x0u, 0x0u, 0x2u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{nullptr,
          "envmap_samplerSphere",
          {0x0u, 0x0u, 0x2u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{nullptr,
          "ps2_shinemap_sampler",
          {0x0u, 0x0u, 0x2u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{nullptr,
          "backBuffer_sampler",
          {0x0u, 0x0u, 0x2u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"wind_sampler",
          nullptr,
          {0x0u, 0x0u, 0x1u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{nullptr,
          "texAnimMap_sampler",
          {0x0u, 0x0u, 0x2u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{nullptr,
          "texAnimCurves_sampler",
          {0x0u, 0x0u, 0x2u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"ambientColor",
          "ambientColor",
          {0x1u, 0x1u, 0x7u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"incandescentGlow",
          "incandescentGlow",
          {0x1u, 0x1u, 0x7u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"bitangentFlip",
          nullptr,
          {0x1u, 0x1u, 0x1u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{nullptr,
          "surface_params",
          {0x1u, 0x1u, 0x6u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{nullptr,
          "surface_params2",
          {0x1u, 0x1u, 0x6u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{nullptr,
          "specular_params",
          {0x1u, 0x1u, 0x2u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{nullptr,
          "envmap_params",
          {0x1u, 0x1u, 0x6u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"vtf_kHeight",
          nullptr,
          {0x1u, 0x1u, 0x5u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{nullptr,
          "vtf_kNormal",
          {0x1u, 0x1u, 0x6u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{nullptr,
          "gooch_params",
          {0x1u, 0x1u, 0x2u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"waterTable",
          nullptr,
          {0x20u, 0x1u, 0x1u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{nullptr,
          "layer0_diffuse",
          {0x1u, 0x1u, 0x6u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{nullptr,
          "layer1_diffuse",
          {0x1u, 0x1u, 0x6u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{nullptr,
          "layer2_diffuse",
          {0x1u, 0x1u, 0x6u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{nullptr,
          "layer3_diffuse",
          {0x1u, 0x1u, 0x6u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{nullptr,
          "layer_kOpacities",
          {0x1u, 0x1u, 0x6u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{nullptr,
          "specular_specular",
          {0x1u, 0x1u, 0x6u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{nullptr,
          "specular2_specular",
          {0x1u, 0x1u, 0x6u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{nullptr,
          "refraction_color",
          {0x1u, 0x1u, 0x6u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{nullptr,
          "refraction_kIndex",
          {0x1u, 0x1u, 0x6u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"uvOffset0",
          nullptr,
          {0x1u, 0x1u, 0x1u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"uvOffset1",
          nullptr,
          {0x1u, 0x1u, 0x1u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"uvOffset2",
          nullptr,
          {0x1u, 0x1u, 0x1u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"uvOffset3",
          nullptr,
          {0x1u, 0x1u, 0x1u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{nullptr,
          "lego_params",
          {0x1u, 0x1u, 0x2u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"fxAttributes",
          nullptr,
          {0x1u, 0x1u, 0x1u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"dappleLimit",
          nullptr,
          {0x1u, 0x1u, 0x1u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{nullptr,
          "carpaint_params",
          {0x1u, 0x1u, 0x2u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{nullptr,
          "carpaint_tints",
          {0x4u, 0x1u, 0x2u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{nullptr,
          "edgelit_params",
          {0x1u, 0x1u, 0x2u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{nullptr,
          "fractal_params",
          {0x1u, 0x1u, 0x2u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{nullptr,
          "alphaTestParameters",
          {0x1u, 0x1u, 0x2u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"vs_sceneAmbientColor",
          "sceneAmbientColor",
          {0x1u, 0x1u, 0x3u, 0x1cu, 0x2u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"vs_lightColor0",
          "lightColor0",
          {0x1u, 0x1u, 0x3u, 0x1du, 0x2u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"vs_lightColor1",
          "lightColor1",
          {0x1u, 0x1u, 0x3u, 0x1eu, 0x2u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"vs_lightColor2",
          "lightColor2",
          {0x1u, 0x1u, 0x3u, 0x1fu, 0x2u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"vs_lightPosition0",
          "lightPosition0",
          {0x1u, 0x1u, 0x3u, 0x20u, 0x2u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"vs_lightPosition1",
          "lightPosition1",
          {0x1u, 0x1u, 0x3u, 0x21u, 0x2u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"vs_lightPosition2",
          "lightPosition2",
          {0x1u, 0x1u, 0x3u, 0x22u, 0x2u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"world",
          nullptr,
          {0x4u, 0x4u, 0x1u, 0x10u, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"vs_view",
          "view",
          {0x4u, 0x4u, 0x3u, 0xcu, 0x1u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"viewProj",
          nullptr,
          {0x4u, 0x4u, 0x1u, 0x0u, 0x2u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"worldViewProj",
          nullptr,
          {0x4u, 0x4u, 0x1u, 0x14u, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"worldView",
          nullptr,
          {0x4u, 0x4u, 0x1u, 0x18u, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"motion",
          nullptr,
          {0x4u, 0x4u, 0x1u, 0x29u, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"vs_lightParams",
          "fs_lightParams",
          {0xbu, 0x1u, 0x3u, 0x1cu, 0x1u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{nullptr,
          "fragmentUniforms_sampler",
          {0x0u, 0x0u, 0x2u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"kTint",
          nullptr,
          {0x1u, 0x1u, 0x1u, 0x28u, 0x2u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"vs_screenSize",
          "fs_screenSize",
          {0x1u, 0x1u, 0x3u, 0x2du, 0x1u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{nullptr,
          "time",
          {0x1u, 0x1u, 0x2u, 0x2eu, 0x1u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{nullptr,
          "fog_color",
          {0x1u, 0x1u, 0x2u, 0x2fu, 0x1u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"fog_params",
          nullptr,
          {0x1u, 0x1u, 0x1u, 0x30u, 0x1u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"vs_projection_params",
          "fs_projection_params",
          {0x1u, 0x1u, 0x3u, 0x31u, 0x1u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"vs_frustum_params",
          "fs_frustum_params",
          {0x1u, 0x1u, 0x3u, 0x32u, 0x1u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"ps2ShineMtx",
          nullptr,
          {0x4u, 0x4u, 0x1u, 0x23u, 0x1u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{nullptr,
          "noiseTexSize",
          {0x1u, 0x1u, 0x2u, 0x40u, 0x1u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"averageLightColor",
          nullptr,
          {0x1u, 0x1u, 0x1u, 0x41u, 0x1u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"averageLightDir",
          nullptr,
          {0x1u, 0x1u, 0x1u, 0x42u, 0x1u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"lightRotationMtx",
          nullptr,
          {0x4u, 0x4u, 0x1u, 0x43u, 0x1u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"offsetTable",
          nullptr,
          {0x8u, 0x1u, 0x1u, 0x47u, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"vertexGroupStates",
          nullptr,
          {0x20u, 0x1u, 0x1u, 0x4fu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"worldParams",
          nullptr,
          {0xcu, 0x4u, 0x1u, 0x10u, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"wind_params",
          nullptr,
          {0x1u, 0x1u, 0x1u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"worldViewInverseTranspose",
          nullptr,
          {0x4u, 0x4u, 0x1u, 0x18u, 0x1u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"vs_viewInverseTranspose",
          "fs_viewInverseTranspose",
          {0x4u, 0x4u, 0x3u, 0xcu, 0x1u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"worldCamPos",
          nullptr,
          {0x1u, 0x1u, 0x1u, 0x27u, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{nullptr,
          "specularDirection",
          {0x1u, 0x1u, 0x2u, 0x33u, 0x2u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"lightmapOffset",
          nullptr,
          {0x1u, 0x1u, 0x1u, 0x34u, 0x1u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"shadowCastingObject",
          nullptr,
          {0x1u, 0x1u, 0x1u, 0x6fu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"skinMatrix",
          nullptr,
          {0x20u, 0x4u, 0x1u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"blendShapesCount",
          nullptr,
          {0x1u, 0x1u, 0x1u, 0x37u, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"blendShapes",
          nullptr,
          {0x10u, 0x1u, 0x1u, 0xffffffffu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"blendShapes[0]",
          nullptr,
          {0x1u, 0x1u, 0x1u, 0x38u, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"blendShapes[1]",
          nullptr,
          {0x1u, 0x1u, 0x1u, 0x39u, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"blendShapes[2]",
          nullptr,
          {0x1u, 0x1u, 0x1u, 0x3au, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"blendShapes[3]",
          nullptr,
          {0x1u, 0x1u, 0x1u, 0x45u, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"blendShapes[4]",
          nullptr,
          {0x1u, 0x1u, 0x1u, 0x3cu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"blendShapes[5]",
          nullptr,
          {0x1u, 0x1u, 0x1u, 0x3du, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"blendShapes[6]",
          nullptr,
          {0x1u, 0x1u, 0x1u, 0x3eu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
        {{"blendShapes[7]",
          nullptr,
          {0x1u, 0x1u, 0x1u, 0x3fu, 0x0u},
          {0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u, 0x0u}}},
    };

    // Uber-shader identity used by key generation (first 8 bytes of the MD5).
    static const u8 kUberShaderHash[16] = {
        0x38, 0x2a, 0x9d, 0x15, 0xf8, 0xfa, 0xbf, 0x09, 0xcb, 0xcc, 0x9b, 0xec, 0x5e, 0xb7, 0x62, 0x40,
    };

    extern "C" void glUniform1fv(GLint, GLsizei, const GLfloat *);
    extern "C" void glUniform2fv(GLint, GLsizei, const GLfloat *);
    extern "C" void glUniform3fv(GLint, GLsizei, const GLfloat *);
    extern "C" void glUniform4fv(GLint, GLsizei, const GLfloat *);

} // namespace nu2api

// ---------------------------------------------------------------------------
// Public C API
// ---------------------------------------------------------------------------

extern "C" void NuShaderManagerInit(VARIPTR *arena, VARIPTR arena_end) {
    VirtualStackAllocator allocator;
    allocator.setExternalMemoryPool(arena->void_ptr, static_cast<u32>(arena_end.addr - arena->addr));
    void *memory = allocator.cursor;
    allocator.cursor += sizeof(ShaderManagerOpenGL);
    g_shaderManager = new (memory) ShaderManagerOpenGL(allocator);
    arena->addr += allocator.cursor - allocator.base;
}

extern "C" NUSHADEROBJECT *NuShaderManagerGetShaderById(i32 id) {
    ShaderManagerOpenGL *manager = static_cast<ShaderManagerOpenGL *>(g_shaderManager);
    if (static_cast<u32>(id) > nu2api::kSlotCount) {
        return NULL;
    }
    return &manager->slots[id];
}

// original 0x318d10 — the manager stores the address of the bound object,
// rather than its numeric shader id.
extern "C" NUSHADEROBJECT *NuShaderManagerGetCurrentShader(void) {
    return static_cast<ShaderManagerOpenGL *>(g_shaderManager)->bound_slot;
}

extern "C" void NuShaderManagerReleaseShader(NUSHADEROBJECT *slot) {
    slot->glsl.base.field1--;
}

extern "C" void NuShaderManagerSetCurrentShader(NUSHADEROBJECT *slot) {
    static_cast<ShaderManagerOpenGL *>(g_shaderManager)->bound_slot = slot;
}

extern "C" void NuShaderManagerDestroyShaders(void) {
    ShaderManagerOpenGL *manager = static_cast<ShaderManagerOpenGL *>(g_shaderManager);
    for (i32 i = 0; i < nu2api::kSlotCount; ++i) {
        NUSHADEROBJECT *slot = &manager->slots[i];
        if (slot->glsl.base.field1 >= 0) {
            NuShaderObjectUnInit(slot);
        }
    }
}

extern "C" void NuShaderManagerDestroy(void) {
    ShaderManagerOpenGL *manager = static_cast<ShaderManagerOpenGL *>(g_shaderManager);
    for (i32 i = 0; i < nu2api::kSlotCount; ++i) {
        NUSHADEROBJECT *slot = &manager->slots[i];
        if (slot->glsl.base.field1 >= 0) {
            NuShaderObjectUnInit(slot);
        }
    }
    g_shaderManager = nullptr;
}

extern "C" void NuShaderManagerSetShaderSaveFolder(const char *folder) {
    std::strcpy(g_shaderSaveFolder, folder);
}

extern u32 g_boundShader;

extern "C" {
    extern void (*g_glConstantSetterTable[4])(u32 location, i32 count, const void *values);
}

extern "C" void NuShaderManagerBindShader(NUSHADEROBJECT *slot) {
    (void)g_shaderManager;
    nu2api::ManagerBoundSlot() = slot;
    if (slot == NULL) {
        return;
    }
    const GLuint program = nu2api::SlotGlProgram(slot);
    if (program != g_boundShader) {
        glUseProgram(program);
        g_boundShader = program;
    }
}

namespace nu2api {

    // ---------------------------------------------------------------------------
    // Material filter helpers
    // ---------------------------------------------------------------------------

    static bool FilterHasDiffuseMap(const ShaderMtlDescFilterPlain *filter, i32 which) {
        const bool extended = (filter->variant == 0) || (filter->desc->unknown_1b4 != 0);
        if (!extended) {
            return false;
        }
        const i32 threshold = filter->param4;
        switch (which) {
            case 0:
                return threshold < filter->desc->diffuse_map_tex_id[0];
            case 1:
                return threshold < filter->desc->diffuse_map_tex_id[1];
            case 2:
                return threshold < filter->desc->diffuse_map_tex_id[2];
            case 3:
                return threshold < filter->desc->diffuse_map_tex_id[3];
            default:
                return false;
        }
    }

    static bool FilterHasLayer(const ShaderMtlDescFilterPlain *filter, i32 layer) {
        const NUSHADERMTLDESC &d = *filter->desc;
        if (filter->variant == 0) {
            switch (layer) {
                case 0:
                    return true;
                case 1:
                    return (d.flagsbits_1b8 & 0x40) != 0 && d.blend_op2 != 0xff;
                case 2:
                    return (static_cast<i8>(d.flagsbits_1b8) < 0) && d.blend_op3 != 0xff;
                case 3:
                    return (d.byte4 & 1) != 0 && d.blend_op4 != 0xff;
                default:
                    return false;
            }
        }
        // Variant path only cares about layer 0.
        return layer == 0 && (d.unknown_1b4 & 1) != 0;
    }

    static u32 FilterGetVertexFlags(const ShaderMtlDescFilterPlain *filter) {
        const NUSHADERMTLDESC *d = filter->desc;
        const u8 *vb = reinterpret_cast<const u8 *>(&d->vtx_desc);

        const u8 attr0 = vb[1]; // 0x13D – texture unit count + low bit
        const u8 attr1 = vb[2]; // 0x13E – packed vertex attribute flags
        const u8 attr2 = vb[3]; // 0x13F – additional attribute bits

        const bool hasPackedPair = (attr1 & 3) != 0;
        const bool hasExtendedPair = (attr1 & 0x40) != 0;
        const u8 texUnitCount = (attr0 >> 1) & 3;
        const bool extended = (filter->variant == 0) || (d->unknown_1b4 != 0);

        u32 flags = (attr1 >> 2) & 1;
        if (hasPackedPair && !hasExtendedPair) {
            flags |= 2;
        }

        if (extended) {
            if (texUnitCount != 0) {
                flags |= 4;
            }
            if (texUnitCount >= 2) {
                flags |= 8;
            }
            if (texUnitCount == 3) {
                flags |= 0x10;
            }
        }

        if (hasPackedPair && hasExtendedPair) {
            flags |= 0x40;
        }
        if (attr1 & 8) {
            flags |= 0x80;
        }
        if (attr2 & 1) {
            flags |= 0x100;
        }
        if (attr2 & 2) {
            flags |= 0x400;
        }

        if (extended) {
            if (static_cast<i8>(d->flagsbits_1bb) < 0) {
                flags |= 0x800;
            }
            if (attr0 & 1) {
                flags |= 0x1000;
            }
        }
        return flags;
    }

    // ---------------------------------------------------------------------------
    // Filter initialisation
    // ---------------------------------------------------------------------------

    static void FilterInternalInit(ShaderMtlDescFilterPlain *filter, const NUSHADERMTLDESC *desc, const void *mtl,
                                   i32 flagsIn, i32 param4) {
        const u8 *mtlBytes = reinterpret_cast<const u8 *>(mtl);

        filter->mtl = mtl;
        filter->param4 = param4;
        filter->desc = desc;
        filter->flags_in = flagsIn;
        filter->variant = flagsIn & 3;

        const bool hasVtxFlag4 = (reinterpret_cast<const u8 *>(&desc->vtx_desc)[2] & 4) != 0;
        const bool hasMtlFlag40 = (mtlBytes[0x41] & 0x40) != 0;
        const bool specialVertexPath = hasVtxFlag4 || hasMtlFlag40;
        const bool baseVariant = filter->variant == 0;
        const bool flag10Path = baseVariant && (flagsIn & 0x10) != 0 && !specialVertexPath;

        filter->field4_0x10 = flag10Path;
        filter->field6_0x18 = !specialVertexPath;

        const bool deferredPath = baseVariant && (flagsIn & 0x20) != 0 && !specialVertexPath;
        filter->field5_0x14 = deferredPath;

        i32 layerCount = 0;
        if (baseVariant) {
            layerCount = (!flag10Path && (desc->flagsbits_1ba & 1) == 0) ? 1 : 2;
        }
        if (filter->field6_0x18 != 0) {
            ++layerCount;
        }
        if (deferredPath) {
            ++layerCount;
        }
        filter->field7_0x1c = layerCount;
    }

} // namespace nu2api

namespace nu2api {

    // ---------------------------------------------------------------------------
    // Key generation
    //
    // Builds the 104-byte descriptor block that is double-hashed (forward +
    // reverse CRC-16) to produce the 32-bit program key. Field names below
    // mirror the Ghidra block layout but are documented by purpose.
    // ---------------------------------------------------------------------------

    extern "C" void NuShaderObjectKeyGenerate3(u32 *outKey, const ::ShaderMtlDescFilter *filter, i32 pixelStage) {
        const NUSHADERMTLDESC *desc = filter->desc;
        const u8 *descBytes = reinterpret_cast<const u8 *>(desc);

        // Fixed 104-byte hash input; zero-initialised then sparsely populated.
        u8 block[0x68] = {};
        block[0x14] = 1;

        u32 flagsWord = 0;
        u8 nibble = 0;

        if (!pixelStage) {
            // Vertex path carries the uber-shader identity.
            block[0x0c] = kUberShaderHash[0];
            block[0x0d] = kUberShaderHash[1];
            block[0x0e] = kUberShaderHash[2];
            block[0x0f] = kUberShaderHash[3];
            block[0x10] = kUberShaderHash[4];
            block[0x11] = kUberShaderHash[5];
            block[0x12] = kUberShaderHash[6];
            block[0x13] = kUberShaderHash[7];

            if (filter->variant != 0) {
                flagsWord = 0x1000;
                nibble = 0;
            } else {
                flagsWord = *reinterpret_cast<const u32 *>(descBytes + 0x1b8) & 0xfffffe3fu;
                nibble = descBytes[0x1bc];
            }
        } else {
            if (filter->variant == 0) {
                flagsWord = *reinterpret_cast<const u32 *>(descBytes + 0x1b8) & 0xfffffe3fu;
                nibble = descBytes[0x1bc];
            } else {
                flagsWord = 0x1000;
                nibble = 0;
            }
        }

        // Filtered flag word (bytes 0x04..0x07, nibble at 0x08, copy at 0x09..0x0b).
        block[0x04] = static_cast<u8>(flagsWord);
        block[0x05] = static_cast<u8>(flagsWord >> 8);
        block[0x06] = static_cast<u8>(flagsWord >> 16);
        block[0x07] = static_cast<u8>(flagsWord >> 24);
        block[0x08] = nibble & 0xf;
        block[0x09] = block[0x04];
        block[0x0a] = block[0x05];
        block[0x0b] = block[0x06];

        // Vertex flags
        const u32 vtxFlags = filter->getVertexFlags();
        block[0x00] = static_cast<u8>(vtxFlags);
        block[0x01] = static_cast<u8>(vtxFlags >> 8);
        block[0x02] = static_cast<u8>(vtxFlags >> 16);
        block[0x03] = static_cast<u8>(vtxFlags >> 24);

        // Filter-derived booleans
        block[0x21] = filter->field_0x10 != 0;
        block[0x22] = filter->field_0x14 != 0;
        block[0x23] = filter->field_0x18 != 0;

        // Auxiliary texture ids: selected only when the base flag / threshold says
        // the texture is actually bound.
        if (filter->variant == 0) {
            const u8 baseFlag = descBytes[0x1b8];
            block[0x15] = ((baseFlag & 1) || (baseFlag & 2)) ? descBytes[0xa9] : 0;
            block[0x16] =
                filter->texture_id_threshold < *reinterpret_cast<const i32 *>(descBytes + 0x48) ? descBytes[0xaa] : 0;
        }

        // Diffuse-map presence + ids
        block[0x17] = static_cast<u8>(filter->hasDiffuseMap(0));
        block[0x18] = filter->hasDiffuseMap(1) ? descBytes[0xab] : 0;
        block[0x19] = filter->hasDiffuseMap(2) ? descBytes[0xac] : 0;
        block[0x1a] = filter->hasDiffuseMap(3) ? descBytes[0xad] : 0;

        // Optional extra map id (0xae)
        if (filter->variant == 0) {
            const u8 b1 = descBytes[0x1b9];
            if ((b1 & 0x20) || (b1 & 0x40)) {
                block[0x1b] = descBytes[0xae];
            }
        }

        // Blend ops for layers 1..3
        block[0x1c] = filter->hasLayer(1) ? desc->blend_op2 : 0;
        block[0x1d] = filter->hasLayer(2) ? desc->blend_op3 : 0;
        block[0x1e] = filter->hasLayer(3) ? desc->blend_op4 : 0;

        // Constants required by the original hashing contract
        block[0x1f] = 1;
        block[0x20] = 1;

        // Shadow / animation variant selectors
        if (filter->variant == 0) {
            const i32 thresholdA = *reinterpret_cast<const i32 *>(descBytes + 0x34);
            const i32 thresholdB = *reinterpret_cast<const i32 *>(descBytes + 0x38);
            const u8 baseFlag = descBytes[0x1b8];

            u8 v24 = 0;
            if ((baseFlag & 1) == 0 || filter->texture_id_threshold >= thresholdB) {
                if ((baseFlag & 2) != 0) {
                    v24 = filter->texture_id_threshold < thresholdB;
                }
            } else {
                v24 = 2;
            }
            block[0x24] = v24;

            const u8 b2 = descBytes[0x1ba];
            block[0x25] = (b2 & 0x10) ? static_cast<u8>((filter->texture_id_threshold < thresholdA) + 1) : 0;
        }

        block[0x26] = *reinterpret_cast<const i32 *>(descBytes + 0x1e4) > 0;
        block[0x27] = *reinterpret_cast<const i32 *>(descBytes + 0x1e8) > 0;

        // Texcoord type heuristic over the material attribute bytes at mtl+0x40..0x42.
        const u8 *mtlBytes = reinterpret_cast<const u8 *>(filter->mtl);
        const u8 unitsLow = (mtlBytes[0x42] >> 4) & 7;
        const u8 vtxType = mtlBytes[0x40] & 0xf;

        bool texcoordIsLong = false;
        if (unitsLow == 3 || unitsLow == 5) {
            texcoordIsLong = true;
        } else {
            texcoordIsLong = (vtxType == 10) || ((unitsLow & 3) == 2);
        }
        const u8 attribC0 = mtlBytes[0x41] & 0xc0;
        if (attribC0 == 0 || attribC0 == 0x80 || vtxType == 0 || vtxType == 10) {
            block[0x28] = texcoordIsLong ? 1 : 0;
        }

        block[0x29] = desc->unknown_a8;

        const u32 hi = CRC16::hashInverse(block, 0x68);
        outKey[0] = hi << 16;
        const u32 lo = CRC16::hash(block, 0x68);
        outKey[0] |= lo & 0xffff;
    }

} // namespace nu2api

namespace nu2api {

    // ---------------------------------------------------------------------------
    // Program creation and cache lookup
    // ---------------------------------------------------------------------------

    // ShaderManagerOpenGL::adaptShaderMaterialForShaderVersion.  Android uses
    // shader version 5, whose generated programs deliberately discard material
    // features unsupported by the mobile uber-shader before the key is built.

    static void *RetrieveShader(void *manager, NUSHADERMTLDESC *desc, void *mtl, i32 variant, i32 flagsIn,
                                bool pixelStage) {
        static_cast<ShaderManagerOpenGL *>(manager)->adaptShaderMaterialForShaderVersion(desc);
        ShaderMtlDescFilterPlain filter{};
        FilterInternalInit(&filter, desc, mtl, variant, flagsIn);
        filter.variant = 0;
        filter.field4_0x10 = 0;
        filter.field5_0x14 = 0;
        filter.field7_0x1c = 1;

        u32 rawKey[4] = {};
        const ::ShaderMtlDescFilter keyFilter = {filter.desc,        static_cast<const numtl_s *>(filter.mtl),
                                                 filter.flags_in,    filter.variant,
                                                 filter.field4_0x10, filter.field5_0x14,
                                                 filter.field6_0x18, filter.field7_0x1c,
                                                 filter.param4};
        NuShaderObjectKeyGenerate3(rawKey, &keyFilter, pixelStage ? 1 : 0);

        ShaderObjectKey programKey{};
        programKey.key[0] = rawKey[0];
        LookupHash(programKey.key[0], &programKey.key[0], g_shaderProgramRedirects, 0x1a1);

        ShaderManagerStorage *storage = static_cast<ShaderManagerStorage *>(manager);

        // Cache hit: bump refcount and return existing slot.
        for (u32 id = 0; id < 0x190; ++id) {
            NUSHADEROBJECT *slot = &storage->slots[id];
            if (SlotProgramKey(slot) == programKey.key[0]) {
                SlotRefCount(slot)++;
                return slot;
            }
        }

        // Cache miss: round-robin over the fixed slot pool.
        const i32 last = ManagerLastAllocated();
        for (i32 step = 1; step <= 0x190; ++step) {
            const i32 id = (last + step) % static_cast<i32>(kSlotCount);
            NUSHADEROBJECT *slot = &storage->slots[id];
            if (SlotRefCount(slot) > 0) {
                continue;
            }
            ManagerLastAllocated() = id;
            if (!storage->createShader(*reinterpret_cast<const ::ShaderObjectKey *>(&programKey),
                                       static_cast<NuShaderObject *>(slot), id)) {
                return nullptr;
            }
            SlotRefCount(slot)++;
            return slot;
        }
        return nullptr;
    }

} // namespace nu2api

// ---------------------------------------------------------------------------
// Wrappers used by the engine
// ---------------------------------------------------------------------------

extern "C" void *NuShaderManagerRetrieveShader(NUSHADERMTLDESC *desc, void *mtl) {
    return nu2api::RetrieveShader(g_shaderManager, desc, mtl, 0, 0, false);
}

extern "C" void *NuShaderManagerRetrieveShaderVariant(NUSHADERMTLDESC *desc, void *mtl, i32 variant) {
    return nu2api::RetrieveShader(g_shaderManager, desc, mtl, variant, 0, false);
}

// GL uniform dispatch table — matches the original .data at 0x65e0b8.
extern "C" {
    void (*g_glConstantSetterTable[4])(u32 loc, i32 count, const void *vals) = {
        reinterpret_cast<void (*)(u32, i32, const void *)>(nu2api::glUniform1fv),
        reinterpret_cast<void (*)(u32, i32, const void *)>(nu2api::glUniform2fv),
        reinterpret_cast<void (*)(u32, i32, const void *)>(nu2api::glUniform3fv),
        reinterpret_cast<void (*)(u32, i32, const void *)>(nu2api::glUniform4fv),
    };
}

extern i32 g_shaderBufferCriticalSection;
bool ShaderManagerOpenGL::createShader(const ::ShaderObjectKey &key, NuShaderObject *outObject, i32 param) {
    using namespace nu2api;

    u32 vertexKey = key.key;
    u32 pixelKey = key.key;

    LookupHash(vertexKey, &vertexKey, g_vertexShaderRedirects, 0x318);
    LookupHash(pixelKey, &pixelKey, g_pixelShaderRedirects, 0x25a);

    GLuint *vertexSlot = nullptr;
    GLuint *pixelSlot = nullptr;
    LookupPreloadedShaderObject(vertexKey, &vertexSlot, g_loadedUniqueVertexShaders, 0x170);
    LookupPreloadedShaderObject(pixelKey, &pixelSlot, g_loadedUniquePixelShaders, 0x22e);

    if (vertexSlot == nullptr || pixelSlot == nullptr) {
        return false;
    }

    // Compile on demand, guarded by the file critical section like the original.
    if (*vertexSlot == 0) {
        NuThreadCriticalSectionBegin(file_criticalsection);
        NuThreadCriticalSectionBegin(g_shaderBufferCriticalSection);
        char *vertexSource;
        i32 vertexSize;
        const bool loaded = LoadShaderSource(&vertexSource, &vertexSize, vertexKey, false);
        const bool compiled =
            loaded && NuShaderObjectGenerateGLSLShader(vertexSlot, GL_VERTEX_SHADER, vertexSource, vertexSize);
        NuThreadCriticalSectionEnd(g_shaderBufferCriticalSection);
        NuThreadCriticalSectionEnd(file_criticalsection);
        if (!compiled) {
            return false;
        }
    }

    if (*pixelSlot == 0) {
        NuThreadCriticalSectionBegin(file_criticalsection);
        NuThreadCriticalSectionBegin(g_shaderBufferCriticalSection);
        char *pixelSource;
        i32 pixelSize;
        const bool loaded = LoadShaderSource(&pixelSource, &pixelSize, pixelKey, true);
        const bool compiled =
            loaded && NuShaderObjectGenerateGLSLShader(pixelSlot, GL_FRAGMENT_SHADER, pixelSource, pixelSize);
        NuThreadCriticalSectionEnd(g_shaderBufferCriticalSection);
        NuThreadCriticalSectionEnd(file_criticalsection);
        if (!compiled) {
            return false;
        }
    }

    NuShaderObjectInit(reinterpret_cast<nushaderobject_s *>(outObject),
                       reinterpret_cast<const nushaderobjectkey_s *>(&key), param, static_cast<u32>(*vertexSlot),
                       static_cast<u32>(*pixelSlot), static_cast<eSHADERVERSION>(5));
    return true;
}

void ShaderManagerOpenGL::adaptShaderMaterialForShaderVersion(NUSHADERMTLDESC *desc) {
    u8 *vtx_desc = reinterpret_cast<u8 *>(&desc->vtx_desc);
    const u8 original_vtx_flags3 = vtx_desc[3];
    u8 mobile_flags3 = desc->flagsbits_1bb;

    if ((original_vtx_flags3 & 4) != 0) {
        mobile_flags3 |= 0x80;
        desc->flags |= 0x200000;
        desc->flagsbits_1bb = mobile_flags3;
    }

    const u8 original_flags0 = desc->flagsbits_1b8;
    const u8 original_flags1 = desc->byte4;
    const u8 original_flags2 = desc->flagsbits_1ba;
    u8 mobile_flags1 = original_flags1 & 0xf7;
    desc->byte4 = mobile_flags1;
    desc->flagsbits_1ba = original_flags2 & 0x7f;

    const u32 packed_mobile_flags = *reinterpret_cast<u32 *>(&desc->flagsbits_1b8);
    u8 mobile_flags0 = original_flags0;
    if ((packed_mobile_flags & 0x04001011) == 0x04001001 && desc->unknown_a8 > 2) {
        mobile_flags0 &= 0x3f;
        desc->flagsbits_1b8 = mobile_flags0;
        desc->byte4 = original_flags1 & 0xf6;
        if ((original_flags0 & 8) == 0) {
            mobile_flags0 |= 0x10;
            desc->flagsbits_1b8 = mobile_flags0;
        }
        mobile_flags1 = desc->byte4;
        desc->normal_map_tid = 0;
    }

    const u32 original_shader_flags = desc->flags;
    mobile_flags0 &= 0xfc;
    desc->flagsbits_1b8 = mobile_flags0;
    desc->flags = original_shader_flags & 0xffff9ffc;
    desc->byte4 = mobile_flags1 & 0x9f;

    if ((original_shader_flags & 0x10000) != 0) {
        mobile_flags0 &= 0xdc;
        desc->flags = original_shader_flags & 0xffff9fdc;
        desc->flagsbits_1b8 = mobile_flags0;
    } else if ((original_shader_flags & 0x20) != 0) {
        mobile_flags0 &= 0xf4;
        desc->flags = original_shader_flags & 0xffff9ff4;
        desc->flagsbits_1b8 = mobile_flags0;
    }

    if ((desc->flags & 0x40200) == 0) {
        desc->flags &= 0xfffffbff;
    }
    desc->byte4 = mobile_flags1 & 0x9b;

    const u32 filtered_shader_flags = desc->flags;
    desc->flagsbits_1b8 = mobile_flags0 & 0xfb;
    const u8 mobile_flags2 = original_flags2 & 0x48;
    desc->flagsbits_1ba = mobile_flags2;
    desc->flags = filtered_shader_flags & 0xf916fffb;
    desc->flagsbits_1bb = mobile_flags3 & 0x27;

    if (::RemoveNormalMaps != 0 && ::RemoveDirectionalMaps != 0) {
        vtx_desc[3] = original_vtx_flags3 & 0xfc;
        desc->normal_map_tid = 0;
        vtx_desc[0] &= 0x0f;
        *reinterpret_cast<i32 *>(reinterpret_cast<u8 *>(desc) + 0x38) = 0;
        desc->flags = filtered_shader_flags & 0xf916fffa;
        if ((mobile_flags3 & 4) != 0) {
            reinterpret_cast<u8 *>(&desc->field_1bc)[0] |= 8;
            desc->flagsbits_1ba = mobile_flags2 | 4;
            desc->flagsbits_1bb = (mobile_flags3 & 0x27) | 4;
        }
    }

    u8 &mobile_capabilities = reinterpret_cast<u8 *>(&desc->field_1bc)[0];
    mobile_capabilities = (mobile_capabilities & 0xfb) | ((NuIOS_IsLowEndDevice() == 0) << 2);
}
