#pragma once

#include "nu2api/nucore/fixed_width.h"

extern i32 LEGOCONTEXT_TUBE;
extern i32 LEGOCONTEXT_GLIDE;
extern i32 LEGOCONTEXT_BLOCK;
extern i32 LEGOCONTEXT_HOLD;
extern i32 LEGOCONTEXT_DROPIN;
extern i32 LEGOCONTEXT_DOOMED;
extern i32 LEGOCONTEXT_LEDGETERRAIN;
extern i32 LEGOCONTEXT_CLIMB;
extern i32 LEGOCONTEXT_HANG;
extern i32 LEGOCONTEXT_JUMP;
extern i32 LEGOCONTEXT_BIGJUMP;
extern i32 LEGOCONTEXT_WALLSHUFFLE;
extern i32 LEGOCONTEXT_COMBO;
extern i32 LEGOCONTEXT_PUNCH;
extern i32 LEGOCONTEXT_PUSH;
extern i32 LEGOCONTEXT_PUSHSPINNER;
extern i32 LEGOCONTEXT_PUSHOBSTACLE;
extern i32 LEGOCONTEXT_BEENTAKENOVER;
extern i32 LEGOCONTEXT_GETIN;
extern i32 LEGOCONTEXT_BUILDIT;
extern i32 LEGOCONTEXT_WEAPONIN;
extern i32 LEGOCONTEXT_WEAPONOUT;
extern i32 LEGOCONTEXT_BACKFLIP;
extern i32 LEGOCONTEXT_WALLJUMPWAIT;
extern i32 LEGOCONTEXT_GRAPPLE;
extern i32 LEGOCONTEXT_SUPERCARRY;
extern i32 LEGOCONTEXT_LAND_JUMP;
extern i32 LEGOCONTEXT_LAND_JUMP2;
extern i32 LEGOCONTEXT_LAND_FLIP;
extern i32 LEGOCONTEXT_LAND_COMBOJUMP;
extern i32 LEGOCONTEXT_LAND_LUNGE;
extern i32 LEGOCONTEXT_LAND_SLAM;
extern i32 LEGOCONTEXT_LAND_SPECIAL;
extern i32 LEGOCONTEXT_LAND_COMBATROLL;
extern i32 LEGOCONTEXT_EATEN;
extern i32 LEGOCONTEXT_SPECIALMOVE_ATTACKER;
extern i32 LEGOCONTEXT_SPECIALMOVE_VICTIM;
extern i32 LEGOCONTEXT_BUCK;
extern i32 LEGOCONTEXT_WHIP;
extern i32 LEGOCONTEXT_NETWAIT;
